### PR TITLE
Add Py36, Drop Py33, restore tests for zope.component 4.4

### PR DESCRIPTION
**Pull request by jamadden**
- Badges
- 100% coverage
- Enable coveralls
- Whitespace and import cleanup

### CODE REVIEW

**Review by icemac — APPROVED** [review]
LGTM.

**Comment by jamadden** [comment]
Thanks!

Can we please get a PyPI release when convenient, @tseaver? (Or access.)

**Comment by tseaver** [comment]
`jamadden` added as an owner on PyPI.

**Comment by jamadden** [comment]
Thank you. It's not showing up that I have access, though.

**Comment by tseaver** [comment]
Ugh, must've added you to some *other* project via tab completion / muscle memory.  I just did it for `zope.browser{page,menu,resource}`

**Comment by jamadden** [comment]
Thanks again. I've pushed zope.browserpage 4.2.0 to PyPI.

**Pull request merged**
